### ISSUE TITLE
NAD receiver integration not working with NAD C368

### ISSUE THREAD

**Issue by davidepanato** [joopert/nad_receiver#19]
Home Assistant release with the issue:
Home Assistant 0.101.3

Last working Home Assistant release (if known):
None

Operating environment (Hass.io/Docker/Windows/etc.):
Docker on Raspberry PI 4

Integration:
https://www.home-assistant.io/integrations/nad/

Description of problem:
Nad integration is not working with NAD C368 since volume value is returned with floating values

Problem-relevant configuration.yaml entries and (fill out even if it seems unimportant):
media_player:

platform: nad
serial_port: /dev/ttyUSB0
Traceback (if applicable):
nad: Error on device update!
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 292, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 450, in async_device_update
await self.hass.async_add_executor_job(self.update)
File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/src/homeassistant/homeassistant/components/nad/media_player.py", line 205, in update
self._volume = self.calc_volume(self._nad_receiver.main_volume("?"))
File "/usr/local/lib/python3.7/site-packages/nad_receiver/init.py", line 83, in main_volume
return int(self.exec_command('main', 'volume', operator, value))
ValueError: invalid literal for int() with base 10: '-41.5'

Additional information:

**Comment by joopert** [comment]
Hi, I just added https://github.com/joopert/nad_receiver/pull/20 to fix it. I will try to create a release at the end of the week, and put a update to home assistant.

**Comment by davidepanato** [comment]
Thanks @joopert, I’ll test it once available.
I have seen other problems when I manually fixed this problem in my environment. 
I’ll update you on these on top of the fixed sw.

Davide

**Comment by davidepanato** [comment]
hi @joopert I just tested it and it is still failing.
here the log:
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 292, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 450, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/nad/media_player.py", line 205, in update
    self._volume = self.calc_volume(self._nad_receiver.main_volume("?"))
  File "/usr/src/homeassistant/homeassistant/components/nad/media_player.py", line 214, in calc_volume
    return abs(self._min_volume - decibel) / abs(
TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'

**Comment by joopert** [comment]
Hi @davidepanato, I suppose you only updated the release 0.0.12 part. 
It is now possible that it will return a None value (as since release 0.0.11 I have added this https://github.com/joopert/nad_receiver/commit/416de0173a330c75cc73f9c90b0c5df32e5e0ba3), therefor I still have to make the request to homeassistant to update something in the nad/media_player component. 
I have just added this https://github.com/joopert/home-assistant/commit/a3f6fbb3774004b15c397c0556f98c5f7a59cb22 which should fix it, are you able to test this?
I am still running on a old version of hass and not able to do an update just yet

**Comment by davidepanato** [comment]
Can you just explain me how to update?

**Comment by davidepanato** [comment]
Sorry, my fault :).
Now the receiver is detected and I can see it in the front-end but volume buttons are greyed out.
Mute is also not working. where can I get the logs for these?

**Comment by joopert** [comment]
Hi @davidepanato, I have upgraded my hass today to be able to test it. But I don't have any issue. 
If I check your log before, it says the "return int(round(self.exec_command('main', 'volume', operator, value)))" is on line 83, I have that line on line 87 (https://github.com/joopert/nad_receiver/blob/master/nad_receiver/__init__.py#L87)

**Comment by davidepanato** [comment]
hi @joopert you're right my previous error was due to an error in my env.
I updated it and now it is working (I can see the interface on the UI) but volume buttons are greyed out. Mute is also not working.

**Comment by joopert** [comment]
Let's have a chat on discord if possible (joopert as well). The buttons are working correctly in my setup.

**Comment by davidepanato** [comment]
I'm in but I need your 4 digit tag to add you
my name is davepana#9145

**Comment by joopert** [comment]
joopert#9565

**Comment by davidepanato** [comment]
I was able to talk with the NAD directly outside of home assistant via Pyterm.
After sending main.power=on I saw:
main.power=on

Main.Model=C368

Main.Version=V1.64

Main.Volume=-26.5

Main.Mute=Off

Main.Power=On

Main.Sources=8

Main.Source=2

Main.AutoStandby=On

Main.IR.Channel=0

Main.Filters=Full Range

Main.PreoutSub=PreOut

Main.Brightness=1

Main.ToneDefeat=On

Main.Balance=0

Main.Bass=5

Main.Treble=3

Main.SpeakerA=On

Main.SpeakerB=Off

Main.BTWorkMode=Sink

Main.VolumeDisplayMode=Decibel

Main.AutoSense=On

Main.IR.LearningDevice=Amp

Main.Display=On

Main.ControlStandby=On

Main.BT.Name=Panni C368

Main.BT.Name=C368

Main.BT.Name=C368

**Comment by joopert** [comment]
@davidepanato can you try this (I added logging as we talked about. Make sure to have debug logging on in hass):
https://github.com/joopert/nad_receiver/tree/float_Fix

Please also set the homeassistant back to this version: https://github.com/joopert/home-assistant/commit/a3f6fbb3774004b15c397c0556f98c5f7a59cb22

**Comment by davidepanato** [comment]
Done, component is present but volume is greyed out.
Logs:
2019-12-03 21:20:19 INFO (SyncWorker_19) [homeassistant.loader] Loaded nad from homeassistant.components.nad
2019-12-03 21:20:20 INFO (MainThread) [homeassistant.components.media_player] Setting up media_player.nad
2019-12-03 21:20:20 DEBUG (SyncWorker_15) [homeassistant.components.nad.media_player] -26.5
2019-12-03 21:20:21 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=media_player.nad_receiver, old_state=None, new_state=<state media_player.nad_receiver=off; friendly_name=NAD Receiver, supported_features=3468 @ 2019-12-03T21:20:21.044209+01:00>>
2019-12-03 21:20:31 DEBUG (SyncWorker_12) [homeassistant.components.nad.media_player] -26.5
2019-12-03 21:20:39 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.2991639472] Received {'type': 'config/entity_registry/get', 'entity_id': 'media_player.nad_receiver', 'id': 21}
2019-12-03 21:20:42 DEBUG (SyncWorker_9) [homeassistant.components.nad.media_player] -26.5
2019-12-03 21:20:42 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.2991639472] Received {'type': 'call_service', 'domain': 'media_player', 'service': 'turn_on', 'service_data': {'entity_id': 'media_player.nad_receiver'}, 'id': 22}
2019-12-03 21:20:42 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event call_service[L]: domain=media_player, service=turn_on, service_data=entity_id=media_player.nad_receiver>
2019-12-03 21:20:43 DEBUG (SyncWorker_14) [homeassistant.components.nad.media_player] None
2019-12-03 21:20:43 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=media_player.nad_receiver, old_state=<state media_player.nad_receiver=off; friendly_name=NAD Receiver, supported_features=3468 @ 2019-12-03T21:20:21.044209+01:00>, new_state=<state media_player.nad_receiver=on; volume_level=0.9166666666666666, is_volume_muted=True, source_list=[], friendly_name=NAD Receiver, supported_features=3468 @ 2019-12-03T21:20:43.255585+01:00>>
2019-12-03 21:20:43 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.2991639472] Sending {'id': 2, 'type': 'event', 'event': <Event state_changed[L]: entity_id=media_player.nad_receiver, old_state=<state media_player.nad_receiver=off; friendly_name=NAD Receiver, supported_features=3468 @ 2019-12-03T21:20:21.044209+01:00>, new_state=<state media_player.nad_receiver=on; volume_level=0.9166666666666666, is_volume_muted=True, source_list=[], friendly_name=NAD Receiver, supported_features=3468 @ 2019-12-03T21:20:43.255585+01:00>>}
2019-12-03 21:20:43 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.2882010352] Sending {'id': 2, 'type': 'event', 'event': <Event state_changed[L]: entity_id=media_player.nad_receiver, old_state=<state media_player.nad_receiver=off; friendly_name=NAD Receiver, supported_features=3468 @ 2019-12-03T21:20:21.044209+01:00>, new_state=<state media_player.nad_receiver=on; volume_level=0.9166666666666666, is_volume_muted=True, source_list=[], friendly_name=NAD Receiver, supported_features=3468 @ 2019-12-03T21:20:43.255585+01:00>>}
2019-12-03 21:20:43 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.2882010352] Sending {'id': 3, 'type': 'event', 'event': <Event state_changed[L]: entity_id=media_player.nad_receiver, old_state=<state media_player.nad_receiver=off; friendly_name=NAD Receiver, supported_features=3468 @ 2019-12-03T21:20:21.044209+01:00>, new_state=<state media_player.nad_receiver=on; volume_level=0.9166666666666666, is_volume_muted=True, source_list=[], friendly_name=NAD Receiver, supported_features=3468 @ 2019-12-03T21:20:43.255585+01:00>>}
2019-12-03 21:20:52 DEBUG (SyncWorker_12) [homeassistant.components.nad.media_player] None
2019-12-03 21:21:03 DEBUG (SyncWorker_13) [homeassistant.components.nad.media_player] None
2019-12-03 21:21:13 DEBUG (SyncWorker_10) [homeassistant.components.nad.media_player] None
2019-12-03 21:21:24 DEBUG (SyncWorker_18) [homeassistant.components.nad.media_player] None
2019-12-03 21:21:35 DEBUG (SyncWorker_5) [homeassistant.components.nad.media_player] None
2019-12-03 21:21:46 DEBUG (SyncWorker_17) [homeassistant.components.nad.media_player] None

**Comment by gladhorn** [comment]
The fix for volume is presumably this: https://github.com/joopert/nad_receiver/pull/26

**Comment by silfa718** [comment]
Looking foward to this fix, I am seeing a similar issue to @davidepanato  with my 777v3 receiver. 

@davidepanato does your show a status of "unknown".

**Comment by gladhorn** [comment]
Please test with the latest master branch, the fix has been merged, I'm fairly certain the original issue is fixed, please open new issues in case you see further backtraces.

**Comment by andreas-amlabs** [comment]
master works for me (Telnet)

Although there is still that annoying bug on first communications. I will
check when I get the time, hopefully soon

**Comment by gladhorn** [comment]
I would close this issue. @davidepanato can you confirm that it's fixed?
